### PR TITLE
refresh crates and packages documentation

### PR DESCRIPTION
**Pull request by TomAFrench**
I've updated the documentation around crates and packages to flesh out our description of different types of crates, etc.
I don't think packages are a large enough topic to warrant a full page to itself so I've merged it with the crates page.

I've borrowed quite liberally from [Rust's book](https://doc.rust-lang.org/book/ch07-00-managing-growing-projects-with-packages-crates-and-modules.html) so we should look a little more like them now.

### CODE REVIEW

**Comment by Globallager** [comment]
Left a minor suggestion; looks great overall though and thanks for putting it up Tom!

We might want to consider throwing in some examples on how to manage crates & packages down the road. cc @noir-lang/developerrelations

**Comment by TomAFrench** [comment]
> Left a minor suggestion; looks great overall though and thanks for putting it up Tom!

Thanks :) Looks like the suggestion got eaten though.

**Review by Globallager — CHANGES_REQUESTED** [review]
Minor suggestion that hopefully helps with readability (especially for devs with less Rust vs Noir context).

**Comment by Globallager** [comment]
> > Left a minor suggestion; looks great overall though and thanks for putting it up Tom!
> 
> Thanks :) Looks like the suggestion got eaten though.

Whoops forgot to actually submit it 😂 just did.

**Pull request merged**
